FROM node:alpine
WORKDIR '/app'
COPY package*.json ./
RUN npm install 
COPY . .
CMD ["npm", "run", "start"]

EXPOSE 80:80


#Ports and volumes 
#docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app {container_id\name}
